import argparse
import os
import re
import sqlite3
import sys
from pathlib import Path

import psycopg


DEFAULT_SQLITE = Path(
    r"C:\Users\dirceu.gerardi\OneDrive - FGV\mapeamento_primeira_infancia_piaui\banco_primeira_infancia_piaui_oficial.sqlite"
)


TABLES = [
    (
        "dim_municipio",
        [
            "cod_ibge",
            "municipio",
            "uf",
            "regiao",
            "fonte",
            "carga_em",
        ],
    ),
    (
        "dim_indicador",
        [
            "indicador_id",
            "eixo",
            "indicador",
            "fonte_principal",
            "status",
            "regra_resumo",
            "carga_em",
        ],
    ),
    (
        "fato_indicador",
        [
            "fato_id",
            "cod_ibge",
            "ano",
            "indicador_id",
            "valor",
            "numerador",
            "denominador",
            "recorte",
            "fonte_valor",
            "carga_em",
        ],
    ),
    (
        "fato_indicador_desagregado",
        [
            "fato_desag_id",
            "cod_ibge",
            "ano",
            "indicador_id",
            "nivel_desagregacao",
            "sexo",
            "raca_cor",
            "idade_mae_faixa",
            "valor",
            "numerador",
            "denominador",
            "recorte",
            "fonte_valor",
            "carga_em",
        ],
    ),
]


def validate_schema_name(schema: str):
    if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", schema):
        raise ValueError(f"Schema invalido: {schema}")


def q_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def create_schema(pg: psycopg.Connection, schema: str):
    s = q_ident(schema)
    ddl = f"""
    CREATE SCHEMA IF NOT EXISTS {s};

    CREATE TABLE IF NOT EXISTS {s}.dim_municipio (
      cod_ibge TEXT PRIMARY KEY,
      municipio TEXT NOT NULL,
      uf TEXT NOT NULL,
      regiao TEXT,
      fonte TEXT,
      carga_em TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS {s}.dim_indicador (
      indicador_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      eixo TEXT NOT NULL,
      indicador TEXT NOT NULL UNIQUE,
      fonte_principal TEXT,
      status TEXT NOT NULL,
      regra_resumo TEXT,
      carga_em TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS {s}.fato_indicador (
      fato_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cod_ibge TEXT NOT NULL,
      ano INTEGER NOT NULL,
      indicador_id BIGINT NOT NULL,
      valor DOUBLE PRECISION,
      numerador DOUBLE PRECISION,
      denominador DOUBLE PRECISION,
      recorte TEXT NOT NULL DEFAULT '',
      fonte_valor TEXT,
      carga_em TEXT NOT NULL,
      UNIQUE (cod_ibge, ano, indicador_id, recorte),
      FOREIGN KEY (cod_ibge) REFERENCES {s}.dim_municipio(cod_ibge),
      FOREIGN KEY (indicador_id) REFERENCES {s}.dim_indicador(indicador_id)
    );

    CREATE TABLE IF NOT EXISTS {s}.fato_indicador_desagregado (
      fato_desag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cod_ibge TEXT NOT NULL,
      ano INTEGER NOT NULL,
      indicador_id BIGINT NOT NULL,
      nivel_desagregacao TEXT NOT NULL,
      sexo TEXT NOT NULL DEFAULT 'Total',
      raca_cor TEXT NOT NULL DEFAULT 'Total',
      idade_mae_faixa TEXT NOT NULL DEFAULT 'Total',
      valor DOUBLE PRECISION,
      numerador DOUBLE PRECISION,
      denominador DOUBLE PRECISION,
      recorte TEXT NOT NULL DEFAULT '',
      fonte_valor TEXT,
      carga_em TEXT NOT NULL,
      UNIQUE (cod_ibge, ano, indicador_id, nivel_desagregacao, sexo, raca_cor, idade_mae_faixa, recorte),
      FOREIGN KEY (cod_ibge) REFERENCES {s}.dim_municipio(cod_ibge),
      FOREIGN KEY (indicador_id) REFERENCES {s}.dim_indicador(indicador_id)
    );

    CREATE INDEX IF NOT EXISTS idx_fato_cod_ano ON {s}.fato_indicador(cod_ibge, ano);
    CREATE INDEX IF NOT EXISTS idx_fato_indicador ON {s}.fato_indicador(indicador_id);
    """
    with pg.cursor() as cur:
        cur.execute(ddl)
    pg.commit()


def truncate_tables(pg: psycopg.Connection, schema: str):
    s = q_ident(schema)
    sql = f"""
    TRUNCATE TABLE
      {s}.fato_indicador_desagregado,
      {s}.fato_indicador,
      {s}.dim_indicador,
      {s}.dim_municipio
    RESTART IDENTITY CASCADE;
    """
    with pg.cursor() as cur:
        cur.execute(sql)
    pg.commit()


def count_sqlite_rows(sqlite_conn: sqlite3.Connection, table: str) -> int:
    cur = sqlite_conn.cursor()
    return int(cur.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0])


def copy_table(sqlite_conn: sqlite3.Connection, pg: psycopg.Connection, schema: str, table: str, columns: list[str]):
    s = q_ident(schema)
    t = q_ident(table)
    cols = ", ".join(q_ident(c) for c in columns)
    sel = f"SELECT {', '.join(columns)} FROM {table}"
    total = count_sqlite_rows(sqlite_conn, table)
    print(f"[{table}] rows={total}")

    scur = sqlite_conn.cursor()
    scur.execute(sel)

    copied = 0
    with pg.cursor() as pcur:
        with pcur.copy(f"COPY {s}.{t} ({cols}) FROM STDIN") as cp:
            while True:
                batch = scur.fetchmany(10000)
                if not batch:
                    break
                for row in batch:
                    cp.write_row(row)
                copied += len(batch)
                if copied % 100000 == 0 or copied == total:
                    print(f"  -> {table}: {copied}/{total}")
    pg.commit()


def reset_identity(pg: psycopg.Connection, schema: str, table: str, id_col: str):
    s = q_ident(schema)
    t = q_ident(table)
    c = q_ident(id_col)
    sql = f"""
    SELECT setval(
      pg_get_serial_sequence('{s}.{t}', '{id_col}'),
      COALESCE((SELECT MAX({c}) FROM {s}.{t}), 1),
      true
    );
    """
    with pg.cursor() as cur:
        cur.execute(sql)
    pg.commit()


def parse_args():
    ap = argparse.ArgumentParser(description="Migrar SQLite local para PostgreSQL cloud")
    ap.add_argument("--sqlite-path", default=str(DEFAULT_SQLITE), help="Caminho do arquivo .sqlite")
    ap.add_argument("--pg-dsn", default=os.getenv("PG_DSN", ""), help="DSN PostgreSQL (ou use env PG_DSN)")
    ap.add_argument("--schema", default="public", help="Schema destino no Postgres (default: public)")
    ap.add_argument(
        "--append",
        action="store_true",
        help="Nao limpa tabelas antes de copiar (default limpa e recarrega)",
    )
    return ap.parse_args()


def main():
    args = parse_args()
    validate_schema_name(args.schema)

    sqlite_path = Path(args.sqlite_path)
    if not sqlite_path.exists():
        raise FileNotFoundError(f"SQLite nao encontrado: {sqlite_path}")
    if not args.pg_dsn:
        raise ValueError("Informe --pg-dsn ou defina a variavel PG_DSN")

    print(f"SQLite: {sqlite_path}")
    print(f"Schema destino: {args.schema}")
    print("Conectando no PostgreSQL...")

    sqlite_conn = sqlite3.connect(str(sqlite_path))
    try:
        with psycopg.connect(args.pg_dsn, autocommit=False) as pg:
            create_schema(pg, args.schema)
            if not args.append:
                print("Limpando tabelas destino...")
                truncate_tables(pg, args.schema)

            for table, cols in TABLES:
                copy_table(sqlite_conn, pg, args.schema, table, cols)

            reset_identity(pg, args.schema, "dim_indicador", "indicador_id")
            reset_identity(pg, args.schema, "fato_indicador", "fato_id")
            reset_identity(pg, args.schema, "fato_indicador_desagregado", "fato_desag_id")

            with pg.cursor() as cur:
                cur.execute(
                    f"""
                    SELECT
                      (SELECT COUNT(*) FROM {q_ident(args.schema)}.dim_municipio),
                      (SELECT COUNT(*) FROM {q_ident(args.schema)}.dim_indicador),
                      (SELECT COUNT(*) FROM {q_ident(args.schema)}.fato_indicador),
                      (SELECT COUNT(*) FROM {q_ident(args.schema)}.fato_indicador_desagregado)
                    """
                )
                n_mun, n_ind, n_fato, n_desag = cur.fetchone()
            print("Migração concluída.")
            print(f"dim_municipio={n_mun}")
            print(f"dim_indicador={n_ind}")
            print(f"fato_indicador={n_fato}")
            print(f"fato_indicador_desagregado={n_desag}")
    finally:
        sqlite_conn.close()


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"ERRO: {e}", file=sys.stderr)
        raise
